//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFlexSoapWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://footballpool.dataaccess.eu", ConfigurationName="DataFlexSoapWebService.InfoSoapType")]
    public interface InfoSoapType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tAllCardsInfo[]> AllCardsInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tPlayerName[]> AllPlayerNamesAsync(bool bSelected);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamPlayerCardInfo[]> AllPlayersWithCardsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamPlayerName[]> AllPlayersWithRoleAsync(string sTeamName, string sRoleCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tStadiumInfo[]> AllStadiumInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamCoachName[]> AllTeamCoachNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> CardsAsync(bool bYellow, int iGameNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> CityNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tCountry[]> CountriesAsync(string sCountryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tGameLevelInfo[]> FirstLastGamesEachLevelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tGameIDsPerCity[]> GameIDsGroupedByCityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tGameResult> GameScoreAsync(int iGameNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GameTeamScoreAsync(int iGameNumber, int iTeamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> GoalsScoredAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.GroupFirstGameDateResponse> GroupFirstGameDateAsync(DataFlexSoapWebService.GroupFirstGameDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tGroupInfo[]> GroupInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.GroupLastGameDateResponse> GroupLastGameDateAsync(DataFlexSoapWebService.GroupLastGameDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tGroupStanding[]> GroupStandingsAsync(int iGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.LevelFirstGameDateResponse> LevelFirstGameDateAsync(DataFlexSoapWebService.LevelFirstGameDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.LevelLastGameDateResponse> LevelLastGameDateAsync(DataFlexSoapWebService.LevelLastGameDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.LevelsResponse> LevelsAsync(DataFlexSoapWebService.LevelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.MatchDatesResponse> MatchDatesAsync(DataFlexSoapWebService.MatchDatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tNextGame[]> NextGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tPlayer[]> PlayersAsync(string sName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tPlayerRole[]> PlayerRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamPlayerCardRankInfo[]> PlayersWithCardsRankedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamPlayerGoalsRankInfo[]> PlayersWithGoalsRankedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tGameResult[]> ResultsAllGamesAsync(int iGroupId, int iLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> StadiumGoogleMapsURLAsync(string sStadiumName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tStadiumInfo> StadiumInfoAsync(string sStadiumName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> StadiumNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.TeamIDsByGroupResponse> TeamIDsByGroupAsync(DataFlexSoapWebService.TeamIDsByGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tPlayer[]> TeamPlayersAsync(string sTeamName, bool bSelected);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> TeamNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tTeam[]> TeamsAsync(string sTeamName);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.tTopScorerTop5[]> TopScorersListAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tAllCardsInfo
    {
        
        private System.DateTime dDateField;
        
        private int iMinuteField;
        
        private string sTeam1NameField;
        
        private string sTeam1FlagField;
        
        private string sTeam2NameField;
        
        private string sTeam2FlagField;
        
        private string sPlayerNameField;
        
        private int iYellowField;
        
        private int iRedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime dDate
        {
            get
            {
                return this.dDateField;
            }
            set
            {
                this.dDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int iMinute
        {
            get
            {
                return this.iMinuteField;
            }
            set
            {
                this.iMinuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sTeam1Name
        {
            get
            {
                return this.sTeam1NameField;
            }
            set
            {
                this.sTeam1NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sTeam1Flag
        {
            get
            {
                return this.sTeam1FlagField;
            }
            set
            {
                this.sTeam1FlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sTeam2Name
        {
            get
            {
                return this.sTeam2NameField;
            }
            set
            {
                this.sTeam2NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sTeam2Flag
        {
            get
            {
                return this.sTeam2FlagField;
            }
            set
            {
                this.sTeam2FlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string sPlayerName
        {
            get
            {
                return this.sPlayerNameField;
            }
            set
            {
                this.sPlayerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int iYellow
        {
            get
            {
                return this.iYellowField;
            }
            set
            {
                this.iYellowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int iRed
        {
            get
            {
                return this.iRedField;
            }
            set
            {
                this.iRedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tTopScorerTop5
    {
        
        private int iRankField;
        
        private int iGoalsField;
        
        private string sNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iRank
        {
            get
            {
                return this.iRankField;
            }
            set
            {
                this.iRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int iGoals
        {
            get
            {
                return this.iGoalsField;
            }
            set
            {
                this.iGoalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tTeam
    {
        
        private int iIdField;
        
        private string sNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iId
        {
            get
            {
                return this.iIdField;
            }
            set
            {
                this.iIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tTeamPlayerGoalsRankInfo
    {
        
        private int iRankField;
        
        private int iIDField;
        
        private string sNameField;
        
        private int iGoalsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iRank
        {
            get
            {
                return this.iRankField;
            }
            set
            {
                this.iRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int iID
        {
            get
            {
                return this.iIDField;
            }
            set
            {
                this.iIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int iGoals
        {
            get
            {
                return this.iGoalsField;
            }
            set
            {
                this.iGoalsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tTeamPlayerCardRankInfo
    {
        
        private int iRankField;
        
        private int iIDField;
        
        private string sNameField;
        
        private int iYellowCardsField;
        
        private int iRedCardsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iRank
        {
            get
            {
                return this.iRankField;
            }
            set
            {
                this.iRankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int iID
        {
            get
            {
                return this.iIDField;
            }
            set
            {
                this.iIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int iYellowCards
        {
            get
            {
                return this.iYellowCardsField;
            }
            set
            {
                this.iYellowCardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int iRedCards
        {
            get
            {
                return this.iRedCardsField;
            }
            set
            {
                this.iRedCardsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tPlayerRole
    {
        
        private string sCodeField;
        
        private string sDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sCode
        {
            get
            {
                return this.sCodeField;
            }
            set
            {
                this.sCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sDescription
        {
            get
            {
                return this.sDescriptionField;
            }
            set
            {
                this.sDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tPlayer
    {
        
        private int iIdField;
        
        private string sNameField;
        
        private string sFullNameField;
        
        private string sFirstNameField;
        
        private string sLastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iId
        {
            get
            {
                return this.iIdField;
            }
            set
            {
                this.iIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sFullName
        {
            get
            {
                return this.sFullNameField;
            }
            set
            {
                this.sFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sFirstName
        {
            get
            {
                return this.sFirstNameField;
            }
            set
            {
                this.sFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sLastName
        {
            get
            {
                return this.sLastNameField;
            }
            set
            {
                this.sLastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tNextGame
    {
        
        private int iGameNumberField;
        
        private string sLocalDateTimeField;
        
        private string sUTCDateTimeField;
        
        private string sTeam1Field;
        
        private string sTeam2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iGameNumber
        {
            get
            {
                return this.iGameNumberField;
            }
            set
            {
                this.iGameNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sLocalDateTime
        {
            get
            {
                return this.sLocalDateTimeField;
            }
            set
            {
                this.sLocalDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sUTCDateTime
        {
            get
            {
                return this.sUTCDateTimeField;
            }
            set
            {
                this.sUTCDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sTeam1
        {
            get
            {
                return this.sTeam1Field;
            }
            set
            {
                this.sTeam1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sTeam2
        {
            get
            {
                return this.sTeam2Field;
            }
            set
            {
                this.sTeam2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tGroupStanding
    {
        
        private int iTeamIdField;
        
        private string sTeamNameField;
        
        private int iPlayedField;
        
        private int iWonField;
        
        private int iDrawField;
        
        private int iLostField;
        
        private int iGoalsForField;
        
        private int iGoalsAgainstField;
        
        private int iPlusMinField;
        
        private int iPointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iTeamId
        {
            get
            {
                return this.iTeamIdField;
            }
            set
            {
                this.iTeamIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sTeamName
        {
            get
            {
                return this.sTeamNameField;
            }
            set
            {
                this.sTeamNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int iPlayed
        {
            get
            {
                return this.iPlayedField;
            }
            set
            {
                this.iPlayedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int iWon
        {
            get
            {
                return this.iWonField;
            }
            set
            {
                this.iWonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int iDraw
        {
            get
            {
                return this.iDrawField;
            }
            set
            {
                this.iDrawField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int iLost
        {
            get
            {
                return this.iLostField;
            }
            set
            {
                this.iLostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int iGoalsFor
        {
            get
            {
                return this.iGoalsForField;
            }
            set
            {
                this.iGoalsForField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int iGoalsAgainst
        {
            get
            {
                return this.iGoalsAgainstField;
            }
            set
            {
                this.iGoalsAgainstField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int iPlusMin
        {
            get
            {
                return this.iPlusMinField;
            }
            set
            {
                this.iPlusMinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int iPoints
        {
            get
            {
                return this.iPointsField;
            }
            set
            {
                this.iPointsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tGroupInfo
    {
        
        private int iIdField;
        
        private int iLevelField;
        
        private string sCodeField;
        
        private string sDescriptionField;
        
        private System.DateTime dFirstGameDateField;
        
        private System.DateTime dLastGameDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iId
        {
            get
            {
                return this.iIdField;
            }
            set
            {
                this.iIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int iLevel
        {
            get
            {
                return this.iLevelField;
            }
            set
            {
                this.iLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sCode
        {
            get
            {
                return this.sCodeField;
            }
            set
            {
                this.sCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sDescription
        {
            get
            {
                return this.sDescriptionField;
            }
            set
            {
                this.sDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime dFirstGameDate
        {
            get
            {
                return this.dFirstGameDateField;
            }
            set
            {
                this.dFirstGameDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime dLastGameDate
        {
            get
            {
                return this.dLastGameDateField;
            }
            set
            {
                this.dLastGameDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tGameResult
    {
        
        private int iGameNumberField;
        
        private string sDescriptionField;
        
        private string dtLocalPlayDateTimeField;
        
        private string dtUTCPlayDateTimeField;
        
        private string sTeamName1Field;
        
        private string sTeamName2Field;
        
        private int iScoreTeam1Field;
        
        private int iScoreTeam2Field;
        
        private int iRedCardsField;
        
        private int iYellowCardsField;
        
        private string sGroupCodeField;
        
        private bool bFinishedField;
        
        private int iPenaltiesWonTeam1Field;
        
        private int iPenaltiesWonTeam2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iGameNumber
        {
            get
            {
                return this.iGameNumberField;
            }
            set
            {
                this.iGameNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sDescription
        {
            get
            {
                return this.sDescriptionField;
            }
            set
            {
                this.sDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dtLocalPlayDateTime
        {
            get
            {
                return this.dtLocalPlayDateTimeField;
            }
            set
            {
                this.dtLocalPlayDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dtUTCPlayDateTime
        {
            get
            {
                return this.dtUTCPlayDateTimeField;
            }
            set
            {
                this.dtUTCPlayDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sTeamName1
        {
            get
            {
                return this.sTeamName1Field;
            }
            set
            {
                this.sTeamName1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string sTeamName2
        {
            get
            {
                return this.sTeamName2Field;
            }
            set
            {
                this.sTeamName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int iScoreTeam1
        {
            get
            {
                return this.iScoreTeam1Field;
            }
            set
            {
                this.iScoreTeam1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int iScoreTeam2
        {
            get
            {
                return this.iScoreTeam2Field;
            }
            set
            {
                this.iScoreTeam2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int iRedCards
        {
            get
            {
                return this.iRedCardsField;
            }
            set
            {
                this.iRedCardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int iYellowCards
        {
            get
            {
                return this.iYellowCardsField;
            }
            set
            {
                this.iYellowCardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string sGroupCode
        {
            get
            {
                return this.sGroupCodeField;
            }
            set
            {
                this.sGroupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool bFinished
        {
            get
            {
                return this.bFinishedField;
            }
            set
            {
                this.bFinishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int iPenaltiesWonTeam1
        {
            get
            {
                return this.iPenaltiesWonTeam1Field;
            }
            set
            {
                this.iPenaltiesWonTeam1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int iPenaltiesWonTeam2
        {
            get
            {
                return this.iPenaltiesWonTeam2Field;
            }
            set
            {
                this.iPenaltiesWonTeam2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tGameIDsPerCity
    {
        
        private string sCityField;
        
        private System.Nullable<int>[] iGameIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sCity
        {
            get
            {
                return this.sCityField;
            }
            set
            {
                this.sCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute()]
        public System.Nullable<int>[] iGameIDs
        {
            get
            {
                return this.iGameIDsField;
            }
            set
            {
                this.iGameIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tGameLevelInfo
    {
        
        private int iLevelField;
        
        private string sLevelCodeField;
        
        private System.DateTime dFirstGameField;
        
        private System.DateTime dtFirstGameTimeField;
        
        private int iFirstGameIDField;
        
        private System.DateTime dLastGameField;
        
        private int iLastGameIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iLevel
        {
            get
            {
                return this.iLevelField;
            }
            set
            {
                this.iLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sLevelCode
        {
            get
            {
                return this.sLevelCodeField;
            }
            set
            {
                this.sLevelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime dFirstGame
        {
            get
            {
                return this.dFirstGameField;
            }
            set
            {
                this.dFirstGameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime dtFirstGameTime
        {
            get
            {
                return this.dtFirstGameTimeField;
            }
            set
            {
                this.dtFirstGameTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int iFirstGameID
        {
            get
            {
                return this.iFirstGameIDField;
            }
            set
            {
                this.iFirstGameIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime dLastGame
        {
            get
            {
                return this.dLastGameField;
            }
            set
            {
                this.dLastGameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int iLastGameID
        {
            get
            {
                return this.iLastGameIDField;
            }
            set
            {
                this.iLastGameIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tCountry
    {
        
        private int iIdField;
        
        private string sNameField;
        
        private string sISOCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iId
        {
            get
            {
                return this.iIdField;
            }
            set
            {
                this.iIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sISOCode
        {
            get
            {
                return this.sISOCodeField;
            }
            set
            {
                this.sISOCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tTeamCoachName
    {
        
        private string sTeamNameField;
        
        private string sCoachNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sTeamName
        {
            get
            {
                return this.sTeamNameField;
            }
            set
            {
                this.sTeamNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sCoachName
        {
            get
            {
                return this.sCoachNameField;
            }
            set
            {
                this.sCoachNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tStadiumInfo
    {
        
        private string sNameField;
        
        private int iSeatsCapacityField;
        
        private string sCityNameField;
        
        private string sWikipediaURLField;
        
        private string sGoogleMapsURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int iSeatsCapacity
        {
            get
            {
                return this.iSeatsCapacityField;
            }
            set
            {
                this.iSeatsCapacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sCityName
        {
            get
            {
                return this.sCityNameField;
            }
            set
            {
                this.sCityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sWikipediaURL
        {
            get
            {
                return this.sWikipediaURLField;
            }
            set
            {
                this.sWikipediaURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sGoogleMapsURL
        {
            get
            {
                return this.sGoogleMapsURLField;
            }
            set
            {
                this.sGoogleMapsURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tTeamPlayerName
    {
        
        private int iIDField;
        
        private string sNameField;
        
        private string sTeamNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iID
        {
            get
            {
                return this.iIDField;
            }
            set
            {
                this.iIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sTeamName
        {
            get
            {
                return this.sTeamNameField;
            }
            set
            {
                this.sTeamNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tTeamPlayerCardInfo
    {
        
        private int iIDField;
        
        private string sNameField;
        
        private int iYellowCardsField;
        
        private int iRedCardsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iID
        {
            get
            {
                return this.iIDField;
            }
            set
            {
                this.iIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int iYellowCards
        {
            get
            {
                return this.iYellowCardsField;
            }
            set
            {
                this.iYellowCardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int iRedCards
        {
            get
            {
                return this.iRedCardsField;
            }
            set
            {
                this.iRedCardsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://footballpool.dataaccess.eu")]
    public partial class tPlayerName
    {
        
        private int iIdField;
        
        private string sNameField;
        
        private string sCountryNameField;
        
        private string sCountryFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int iId
        {
            get
            {
                return this.iIdField;
            }
            set
            {
                this.iIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sName
        {
            get
            {
                return this.sNameField;
            }
            set
            {
                this.sNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sCountryName
        {
            get
            {
                return this.sCountryNameField;
            }
            set
            {
                this.sCountryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sCountryFlag
        {
            get
            {
                return this.sCountryFlagField;
            }
            set
            {
                this.sCountryFlagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupFirstGameDate", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class GroupFirstGameDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        public string sGroupCode;
        
        public GroupFirstGameDateRequest()
        {
        }
        
        public GroupFirstGameDateRequest(string sGroupCode)
        {
            this.sGroupCode = sGroupCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupFirstGameDateResponse", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class GroupFirstGameDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime GroupFirstGameDateResult;
        
        public GroupFirstGameDateResponse()
        {
        }
        
        public GroupFirstGameDateResponse(System.DateTime GroupFirstGameDateResult)
        {
            this.GroupFirstGameDateResult = GroupFirstGameDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupLastGameDate", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class GroupLastGameDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        public string sGroupCode;
        
        public GroupLastGameDateRequest()
        {
        }
        
        public GroupLastGameDateRequest(string sGroupCode)
        {
            this.sGroupCode = sGroupCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GroupLastGameDateResponse", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class GroupLastGameDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime GroupLastGameDateResult;
        
        public GroupLastGameDateResponse()
        {
        }
        
        public GroupLastGameDateResponse(System.DateTime GroupLastGameDateResult)
        {
            this.GroupLastGameDateResult = GroupLastGameDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LevelFirstGameDate", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class LevelFirstGameDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        public int iLevel;
        
        public LevelFirstGameDateRequest()
        {
        }
        
        public LevelFirstGameDateRequest(int iLevel)
        {
            this.iLevel = iLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LevelFirstGameDateResponse", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class LevelFirstGameDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LevelFirstGameDateResult;
        
        public LevelFirstGameDateResponse()
        {
        }
        
        public LevelFirstGameDateResponse(System.DateTime LevelFirstGameDateResult)
        {
            this.LevelFirstGameDateResult = LevelFirstGameDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LevelLastGameDate", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class LevelLastGameDateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        public int iLevel;
        
        public LevelLastGameDateRequest()
        {
        }
        
        public LevelLastGameDateRequest(int iLevel)
        {
            this.iLevel = iLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LevelLastGameDateResponse", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class LevelLastGameDateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LevelLastGameDateResult;
        
        public LevelLastGameDateResponse()
        {
        }
        
        public LevelLastGameDateResponse(System.DateTime LevelLastGameDateResult)
        {
            this.LevelLastGameDateResult = LevelLastGameDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Levels", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class LevelsRequest
    {
        
        public LevelsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LevelsResponse", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class LevelsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute()]
        public System.Nullable<int>[] LevelsResult;
        
        public LevelsResponse()
        {
        }
        
        public LevelsResponse(System.Nullable<int>[] LevelsResult)
        {
            this.LevelsResult = LevelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MatchDates", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class MatchDatesRequest
    {
        
        public MatchDatesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MatchDatesResponse", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class MatchDatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(DataType="date")]
        public System.Nullable<System.DateTime>[] MatchDatesResult;
        
        public MatchDatesResponse()
        {
        }
        
        public MatchDatesResponse(System.Nullable<System.DateTime>[] MatchDatesResult)
        {
            this.MatchDatesResult = MatchDatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TeamIDsByGroup", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class TeamIDsByGroupRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        public string sGroupCode;
        
        public TeamIDsByGroupRequest()
        {
        }
        
        public TeamIDsByGroupRequest(string sGroupCode)
        {
            this.sGroupCode = sGroupCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TeamIDsByGroupResponse", WrapperNamespace="https://footballpool.dataaccess.eu", IsWrapped=true)]
    public partial class TeamIDsByGroupResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://footballpool.dataaccess.eu", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute()]
        public System.Nullable<int>[] TeamIDsByGroupResult;
        
        public TeamIDsByGroupResponse()
        {
        }
        
        public TeamIDsByGroupResponse(System.Nullable<int>[] TeamIDsByGroupResult)
        {
            this.TeamIDsByGroupResult = TeamIDsByGroupResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface InfoSoapTypeChannel : DataFlexSoapWebService.InfoSoapType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class InfoSoapTypeClient : System.ServiceModel.ClientBase<DataFlexSoapWebService.InfoSoapType>, DataFlexSoapWebService.InfoSoapType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InfoSoapTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(InfoSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), InfoSoapTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InfoSoapTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InfoSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InfoSoapTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InfoSoapTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InfoSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tAllCardsInfo[]> AllCardsInfoAsync()
        {
            return base.Channel.AllCardsInfoAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tPlayerName[]> AllPlayerNamesAsync(bool bSelected)
        {
            return base.Channel.AllPlayerNamesAsync(bSelected);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamPlayerCardInfo[]> AllPlayersWithCardsAsync()
        {
            return base.Channel.AllPlayersWithCardsAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamPlayerName[]> AllPlayersWithRoleAsync(string sTeamName, string sRoleCode)
        {
            return base.Channel.AllPlayersWithRoleAsync(sTeamName, sRoleCode);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tStadiumInfo[]> AllStadiumInfoAsync()
        {
            return base.Channel.AllStadiumInfoAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamCoachName[]> AllTeamCoachNamesAsync()
        {
            return base.Channel.AllTeamCoachNamesAsync();
        }
        
        public System.Threading.Tasks.Task<int> CardsAsync(bool bYellow, int iGameNumber)
        {
            return base.Channel.CardsAsync(bYellow, iGameNumber);
        }
        
        public System.Threading.Tasks.Task<string[]> CityNamesAsync()
        {
            return base.Channel.CityNamesAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tCountry[]> CountriesAsync(string sCountryName)
        {
            return base.Channel.CountriesAsync(sCountryName);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tGameLevelInfo[]> FirstLastGamesEachLevelAsync()
        {
            return base.Channel.FirstLastGamesEachLevelAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tGameIDsPerCity[]> GameIDsGroupedByCityAsync()
        {
            return base.Channel.GameIDsGroupedByCityAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tGameResult> GameScoreAsync(int iGameNumber)
        {
            return base.Channel.GameScoreAsync(iGameNumber);
        }
        
        public System.Threading.Tasks.Task<int> GameTeamScoreAsync(int iGameNumber, int iTeamId)
        {
            return base.Channel.GameTeamScoreAsync(iGameNumber, iTeamId);
        }
        
        public System.Threading.Tasks.Task<int> GoalsScoredAsync()
        {
            return base.Channel.GoalsScoredAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.GroupFirstGameDateResponse> DataFlexSoapWebService.InfoSoapType.GroupFirstGameDateAsync(DataFlexSoapWebService.GroupFirstGameDateRequest request)
        {
            return base.Channel.GroupFirstGameDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.GroupFirstGameDateResponse> GroupFirstGameDateAsync(string sGroupCode)
        {
            DataFlexSoapWebService.GroupFirstGameDateRequest inValue = new DataFlexSoapWebService.GroupFirstGameDateRequest();
            inValue.sGroupCode = sGroupCode;
            return ((DataFlexSoapWebService.InfoSoapType)(this)).GroupFirstGameDateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tGroupInfo[]> GroupInfoAsync()
        {
            return base.Channel.GroupInfoAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.GroupLastGameDateResponse> DataFlexSoapWebService.InfoSoapType.GroupLastGameDateAsync(DataFlexSoapWebService.GroupLastGameDateRequest request)
        {
            return base.Channel.GroupLastGameDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.GroupLastGameDateResponse> GroupLastGameDateAsync(string sGroupCode)
        {
            DataFlexSoapWebService.GroupLastGameDateRequest inValue = new DataFlexSoapWebService.GroupLastGameDateRequest();
            inValue.sGroupCode = sGroupCode;
            return ((DataFlexSoapWebService.InfoSoapType)(this)).GroupLastGameDateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tGroupStanding[]> GroupStandingsAsync(int iGroupId)
        {
            return base.Channel.GroupStandingsAsync(iGroupId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.LevelFirstGameDateResponse> DataFlexSoapWebService.InfoSoapType.LevelFirstGameDateAsync(DataFlexSoapWebService.LevelFirstGameDateRequest request)
        {
            return base.Channel.LevelFirstGameDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.LevelFirstGameDateResponse> LevelFirstGameDateAsync(int iLevel)
        {
            DataFlexSoapWebService.LevelFirstGameDateRequest inValue = new DataFlexSoapWebService.LevelFirstGameDateRequest();
            inValue.iLevel = iLevel;
            return ((DataFlexSoapWebService.InfoSoapType)(this)).LevelFirstGameDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.LevelLastGameDateResponse> DataFlexSoapWebService.InfoSoapType.LevelLastGameDateAsync(DataFlexSoapWebService.LevelLastGameDateRequest request)
        {
            return base.Channel.LevelLastGameDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.LevelLastGameDateResponse> LevelLastGameDateAsync(int iLevel)
        {
            DataFlexSoapWebService.LevelLastGameDateRequest inValue = new DataFlexSoapWebService.LevelLastGameDateRequest();
            inValue.iLevel = iLevel;
            return ((DataFlexSoapWebService.InfoSoapType)(this)).LevelLastGameDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.LevelsResponse> DataFlexSoapWebService.InfoSoapType.LevelsAsync(DataFlexSoapWebService.LevelsRequest request)
        {
            return base.Channel.LevelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.LevelsResponse> LevelsAsync()
        {
            DataFlexSoapWebService.LevelsRequest inValue = new DataFlexSoapWebService.LevelsRequest();
            return ((DataFlexSoapWebService.InfoSoapType)(this)).LevelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.MatchDatesResponse> DataFlexSoapWebService.InfoSoapType.MatchDatesAsync(DataFlexSoapWebService.MatchDatesRequest request)
        {
            return base.Channel.MatchDatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.MatchDatesResponse> MatchDatesAsync()
        {
            DataFlexSoapWebService.MatchDatesRequest inValue = new DataFlexSoapWebService.MatchDatesRequest();
            return ((DataFlexSoapWebService.InfoSoapType)(this)).MatchDatesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tNextGame[]> NextGamesAsync()
        {
            return base.Channel.NextGamesAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tPlayer[]> PlayersAsync(string sName)
        {
            return base.Channel.PlayersAsync(sName);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tPlayerRole[]> PlayerRolesAsync()
        {
            return base.Channel.PlayerRolesAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamPlayerCardRankInfo[]> PlayersWithCardsRankedAsync()
        {
            return base.Channel.PlayersWithCardsRankedAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tTeamPlayerGoalsRankInfo[]> PlayersWithGoalsRankedAsync()
        {
            return base.Channel.PlayersWithGoalsRankedAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tGameResult[]> ResultsAllGamesAsync(int iGroupId, int iLevel)
        {
            return base.Channel.ResultsAllGamesAsync(iGroupId, iLevel);
        }
        
        public System.Threading.Tasks.Task<string> StadiumGoogleMapsURLAsync(string sStadiumName)
        {
            return base.Channel.StadiumGoogleMapsURLAsync(sStadiumName);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tStadiumInfo> StadiumInfoAsync(string sStadiumName)
        {
            return base.Channel.StadiumInfoAsync(sStadiumName);
        }
        
        public System.Threading.Tasks.Task<string[]> StadiumNamesAsync()
        {
            return base.Channel.StadiumNamesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataFlexSoapWebService.TeamIDsByGroupResponse> DataFlexSoapWebService.InfoSoapType.TeamIDsByGroupAsync(DataFlexSoapWebService.TeamIDsByGroupRequest request)
        {
            return base.Channel.TeamIDsByGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.TeamIDsByGroupResponse> TeamIDsByGroupAsync(string sGroupCode)
        {
            DataFlexSoapWebService.TeamIDsByGroupRequest inValue = new DataFlexSoapWebService.TeamIDsByGroupRequest();
            inValue.sGroupCode = sGroupCode;
            return ((DataFlexSoapWebService.InfoSoapType)(this)).TeamIDsByGroupAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tPlayer[]> TeamPlayersAsync(string sTeamName, bool bSelected)
        {
            return base.Channel.TeamPlayersAsync(sTeamName, bSelected);
        }
        
        public System.Threading.Tasks.Task<string[]> TeamNamesAsync()
        {
            return base.Channel.TeamNamesAsync();
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tTeam[]> TeamsAsync(string sTeamName)
        {
            return base.Channel.TeamsAsync(sTeamName);
        }
        
        public System.Threading.Tasks.Task<DataFlexSoapWebService.tTopScorerTop5[]> TopScorersListAsync()
        {
            return base.Channel.TopScorersListAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InfoSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.InfoSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InfoSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.footballpool.dataaccess.eu/info.wso");
            }
            if ((endpointConfiguration == EndpointConfiguration.InfoSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.footballpool.dataaccess.eu/info.wso");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            InfoSoap,
            
            InfoSoap12,
        }
    }
}
